spring.application.name=wtc-application
spring.jpa.hibernate.ddl-auto=none


spring.rabbitmq.host=127.0.0.1
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


spring.internal.amqp.serialization.type=json




#recomendável mudar para teste
spring.profiles.active=docker

spring.rabbitmq.listener.simple.auto-startup=true



spring.flyway.locations=classpath:db/migration


api.security.token.secret=${JWT_SECRET:123}
spring.flyway.enabled=false
