-- 1. wtc_participants
CREATE TABLE wtc_participants (
                                  id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  participant_type VARCHAR2(255),
                                  ref_id NUMBER(19)
);

-- 2. wtc_authenticable_users
CREATE TABLE wtc_authenticable_users (
                                         id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         email VARCHAR2(255) NOT NULL UNIQUE,
                                         password VARCHAR2(255) NOT NULL,
                                         role VARCHAR2(255) NOT NULL,
                                         participant_id NUMBER(19) UNIQUE,
                                         CONSTRAINT fk_auth_user_participant FOREIGN KEY (participant_id) REFERENCES wtc_participants(id)
);

-- 3. wtc_users
CREATE TABLE wtc_users (
                           id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           full_name VARCHAR2(255) NOT NULL,
                           active NUMBER(1,0) DEFAULT 1 NOT NULL,
                           participant_id NUMBER(19) UNIQUE,
                           authenticable_user_id NUMBER(19) UNIQUE,
                           created_at TIMESTAMP,
                           updated_at TIMESTAMP,
                           deleted NUMBER(1,0),
                           CONSTRAINT fk_user_participant FOREIGN KEY (participant_id) REFERENCES wtc_participants(id),
                           CONSTRAINT fk_user_auth_user FOREIGN KEY (authenticable_user_id) REFERENCES wtc_authenticable_users(id)
);

-- 4. wtc_tags
CREATE TABLE wtc_tags (
                          id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR2(255) NOT NULL UNIQUE,
                          color VARCHAR2(255),
                          description CLOB,
                          created_at TIMESTAMP,
                          deleted NUMBER(1,0)
);

-- 5. wtc_segments
CREATE TABLE wtc_segments (
                              id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name VARCHAR2(255) NOT NULL UNIQUE,
                              description CLOB,
                              active NUMBER(1,0) DEFAULT 1 NOT NULL,
                              created_at TIMESTAMP,
                              deleted NUMBER(1,0) DEFAULT 0 NOT NULL
);

-- 6. wtc_clients
CREATE TABLE wtc_clients (
                             id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             full_name VARCHAR2(255) NOT NULL,
                             phone_number VARCHAR2(255),
                             company_name VARCHAR2(255),
                             notes VARCHAR2(1000),
                             active NUMBER(1,0) DEFAULT 1 NOT NULL,
                             participant_id NUMBER(19) UNIQUE,
                             authenticable_user_id NUMBER(19) UNIQUE,
                             firebase_token CLOB,
                             created_at TIMESTAMP,
                             updated_at TIMESTAMP,
                             deleted NUMBER(1,0),
                             CONSTRAINT fk_client_participant FOREIGN KEY (participant_id) REFERENCES wtc_participants(id),
                             CONSTRAINT fk_client_auth_user FOREIGN KEY (authenticable_user_id) REFERENCES wtc_authenticable_users(id)
);

-- 7. wtc_conversations
CREATE TABLE wtc_conversations (
                                   id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   title VARCHAR2(255),
                                   last_message_at TIMESTAMP,
                                   created_at TIMESTAMP NOT NULL,
                                   updated_at TIMESTAMP,
                                   deleted NUMBER(1,0) DEFAULT 0 NOT NULL,
                                   active NUMBER(1,0) DEFAULT 1 NOT NULL,
                                   status VARCHAR2(255) NOT NULL,
                                   assigned_operator_id NUMBER(19),
                                   origin VARCHAR2(255) NOT NULL,
                                   conversation_type_origin VARCHAR2(255),
                                   CONSTRAINT fk_conv_operator FOREIGN KEY (assigned_operator_id) REFERENCES wtc_participants(id)
);

-- 8. wtc_campaigns
CREATE TABLE wtc_campaigns (
                               id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               title VARCHAR2(255) NOT NULL,
                               content CLOB NOT NULL,
                               status VARCHAR2(255) NOT NULL,
                               creator_id NUMBER(19) NOT NULL,
                               target_segment_id NUMBER(19) NOT NULL,
                               send_notification NUMBER(1,0) DEFAULT 0 NOT NULL,
                               scheduled_at TIMESTAMP,
                               sent_at TIMESTAMP,
                               created_at TIMESTAMP NOT NULL,
                               updated_at TIMESTAMP NOT NULL,
                               deleted NUMBER(1,0) DEFAULT 0 NOT NULL,
                               internal_route VARCHAR2(255) NOT NULL,
                               campaign_code VARCHAR2(255) NOT NULL UNIQUE,
                               CONSTRAINT fk_campaign_creator FOREIGN KEY (creator_id) REFERENCES wtc_users(id),
                               CONSTRAINT fk_campaign_segment FOREIGN KEY (target_segment_id) REFERENCES wtc_segments(id)
);

-- 9. wtc_campaign_metrics
CREATE TABLE wtc_campaign_metrics (
                                      id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      campaign_id NUMBER(19) NOT NULL UNIQUE,
                                      clicks_count NUMBER(19) DEFAULT 0 NOT NULL,
                                      updated_at TIMESTAMP,
                                      deleted NUMBER(1,0),
                                      CONSTRAINT fk_metric_campaign FOREIGN KEY (campaign_id) REFERENCES wtc_campaigns(id)
);

-- 10. wtc_messages
CREATE TABLE wtc_messages (
                              id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              content CLOB NOT NULL,
                              status VARCHAR2(255) NOT NULL,
                              type VARCHAR2(255) NOT NULL,
                              sender_id NUMBER(19),
                              receiver_id NUMBER(19),
                              conversation_id NUMBER(19) NOT NULL,
                              campaign_id NUMBER(19),
                              is_read NUMBER(1,0) DEFAULT 0 NOT NULL,
                              sent_at TIMESTAMP NOT NULL,
                              created_at TIMESTAMP,
                              deleted NUMBER(1,0) DEFAULT 0 NOT NULL,
                              CONSTRAINT fk_msg_sender FOREIGN KEY (sender_id) REFERENCES wtc_participants(id),
                              CONSTRAINT fk_msg_receiver FOREIGN KEY (receiver_id) REFERENCES wtc_participants(id),
                              CONSTRAINT fk_msg_conversation FOREIGN KEY (conversation_id) REFERENCES wtc_conversations(id),
                              CONSTRAINT fk_msg_campaign FOREIGN KEY (campaign_id) REFERENCES wtc_campaigns(id)
);

-- 11. wtc_notifications
CREATE TABLE wtc_notifications (
                                   id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   conversation_id NUMBER(19),
                                   receiver_id NUMBER(19),
                                   preview_content VARCHAR2(255),
                                   is_read NUMBER(1,0) DEFAULT 0,
                                   created_at TIMESTAMP,
                                   CONSTRAINT fk_notif_conversation FOREIGN KEY (conversation_id) REFERENCES wtc_conversations(id) ON DELETE CASCADE,
                                   CONSTRAINT fk_notif_receiver FOREIGN KEY (receiver_id) REFERENCES wtc_participants(id)
);

-- 12. wtc_audits
CREATE TABLE wtc_audits (
                            id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            action VARCHAR2(255) NOT NULL,
                            details CLOB,
                            create_at TIMESTAMP,
                            user_id NUMBER(19),
                            entity_id NUMBER(19),
                            entity_name VARCHAR2(255),
                            deleted NUMBER(1,0),
                            CONSTRAINT fk_audit_user FOREIGN KEY (user_id) REFERENCES wtc_users(id)
);

-- Tabelas de Relacionamento (Many-to-Many)

CREATE TABLE wtc_user_segments (
                                   user_id NUMBER(19) NOT NULL,
                                   segment_id NUMBER(19) NOT NULL,
                                   PRIMARY KEY (user_id, segment_id),
                                   CONSTRAINT fk_us_user FOREIGN KEY (user_id) REFERENCES wtc_users(id),
                                   CONSTRAINT fk_us_segment FOREIGN KEY (segment_id) REFERENCES wtc_segments(id)
);

CREATE TABLE wtc_client_tags (
                                 client_id NUMBER(19) NOT NULL,
                                 tag_id NUMBER(19) NOT NULL,
                                 PRIMARY KEY (client_id, tag_id),
                                 CONSTRAINT fk_ct_client FOREIGN KEY (client_id) REFERENCES wtc_clients(id),
                                 CONSTRAINT fk_ct_tag FOREIGN KEY (tag_id) REFERENCES wtc_tags(id)
);

CREATE TABLE wtc_client_segments (
                                     client_id NUMBER(19) NOT NULL,
                                     segment_id NUMBER(19) NOT NULL,
                                     PRIMARY KEY (client_id, segment_id),
                                     CONSTRAINT fk_cs_client FOREIGN KEY (client_id) REFERENCES wtc_clients(id),
                                     CONSTRAINT fk_cs_segment FOREIGN KEY (segment_id) REFERENCES wtc_segments(id)
);

CREATE TABLE wtc_conversation_participants (
                                               conversation_id NUMBER(19) NOT NULL,
                                               participant_id NUMBER(19) NOT NULL,
                                               PRIMARY KEY (conversation_id, participant_id),
                                               CONSTRAINT fk_cp_conversation FOREIGN KEY (conversation_id) REFERENCES wtc_conversations(id),
                                               CONSTRAINT fk_cp_participant FOREIGN KEY (participant_id) REFERENCES wtc_participants(id)
);