-- V1__create_wtc_schema.sql
-- Base schema for WTC CRM

CREATE TABLE wtc_users (
                           id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           full_name VARCHAR(255) NOT NULL,
                           email VARCHAR(255) NOT NULL,
                           password VARCHAR(255) NOT NULL,
                           role VARCHAR(50) NOT NULL,
                           active NUMBER(1) DEFAULT 1 NOT NULL,
                           created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                           deleted NUMBER(1) DEFAULT 0,
                           CONSTRAINT uk_wtc_users_email UNIQUE (email)
);

CREATE TABLE wtc_clients (
                             id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             full_name VARCHAR(255) NOT NULL,
                             email VARCHAR(255) NOT NULL,
                             password VARCHAR(255) NOT NULL,
                             phone_number VARCHAR(50),
                             company_name VARCHAR(255),
                             notes CLOB,
                             active NUMBER(1) DEFAULT 1 NOT NULL,
                             created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                             deleted NUMBER(1) DEFAULT 0,
                             CONSTRAINT uk_wtc_clients_email UNIQUE (email)
);

CREATE TABLE wtc_segments (
                              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name VARCHAR(255) NOT NULL,
                              description CLOB,
                              active NUMBER(1) DEFAULT 1 NOT NULL,
                              created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              deleted NUMBER(1) DEFAULT 0,
                              CONSTRAINT uk_wtc_segments_name UNIQUE (name)
);

CREATE TABLE wtc_tags (
                          id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name VARCHAR(255) NOT NULL,
                          color VARCHAR(100),
                          description CLOB,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          deleted NUMBER(1) DEFAULT 0,
                          CONSTRAINT uk_wtc_tags_name UNIQUE (name)
);

CREATE TABLE wtc_campaigns (
                               id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               title VARCHAR(255) NOT NULL,
                               content CLOB NOT NULL,
                               status VARCHAR(50) NOT NULL,
                               creator_id NUMBER NOT NULL,
                               target_segment_id NUMBER NOT NULL,
                               send_notification NUMBER(1) DEFAULT 1 NOT NULL,
                               scheduled_at TIMESTAMP,
                               sent_at TIMESTAMP,
                               created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                               deleted NUMBER(1) DEFAULT 0,
                               CONSTRAINT fk_wtc_campaigns_creator
                                   FOREIGN KEY (creator_id) REFERENCES wtc_users (id),
                               CONSTRAINT fk_wtc_campaigns_target_segment
                                   FOREIGN KEY (target_segment_id) REFERENCES wtc_segments (id)
);

CREATE TABLE wtc_campaign_metrics (
                                      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      total_sent INTEGER DEFAULT 0 NOT NULL,
                                      total_opened INTEGER DEFAULT 0 NOT NULL,
                                      total_failed INTEGER DEFAULT 0 NOT NULL,
                                      campaign_id NUMBER NOT NULL,
                                      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                      deleted NUMBER(1) DEFAULT 0,
                                      CONSTRAINT uk_wtc_campaign_metrics_campaign UNIQUE (campaign_id),
                                      CONSTRAINT fk_wtc_campaign_metrics_campaign
                                          FOREIGN KEY (campaign_id) REFERENCES wtc_campaigns (id)
);

CREATE TABLE wtc_conversations (
                                   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   client_id NUMBER NOT NULL,
                                   operator_id NUMBER,
                                   active NUMBER(1) DEFAULT 1 NOT NULL,
                                   last_message_at TIMESTAMP,
                                   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                   updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                   deleted NUMBER(1) DEFAULT 0,
                                   CONSTRAINT fk_wtc_conversations_client
                                       FOREIGN KEY (client_id) REFERENCES wtc_clients (id),
                                   CONSTRAINT fk_wtc_conversations_operator
                                       FOREIGN KEY (operator_id) REFERENCES wtc_users (id)
);

CREATE TABLE wtc_messages (
                              id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              content CLOB NOT NULL,
                              status VARCHAR(50) NOT NULL,
                              sender_type VARCHAR(50) NOT NULL,
                              sent_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              is_read NUMBER(1) DEFAULT 0 NOT NULL,
                              conversation_id NUMBER NOT NULL,
                              sender_user_id NUMBER,
                              sender_client_id NUMBER,
                              campaign_id NUMBER,
                              deleted NUMBER(1) DEFAULT 0,
                              CONSTRAINT fk_wtc_messages_conversation
                                  FOREIGN KEY (conversation_id) REFERENCES wtc_conversations (id),
                              CONSTRAINT fk_wtc_messages_sender_user
                                  FOREIGN KEY (sender_user_id) REFERENCES wtc_users (id),
                              CONSTRAINT fk_wtc_messages_sender_client
                                  FOREIGN KEY (sender_client_id) REFERENCES wtc_clients (id),
                              CONSTRAINT fk_wtc_messages_campaign
                                  FOREIGN KEY (campaign_id) REFERENCES wtc_campaigns (id)
);

CREATE TABLE wtc_notifications (
                                   id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   title VARCHAR(255) NOT NULL,
                                   body CLOB NOT NULL,
                                   image_url VARCHAR(500),
                                   status VARCHAR(50) NOT NULL,
                                   is_read NUMBER(1) DEFAULT 0 NOT NULL,
                                   fcm_message_id VARCHAR(255),
                                   error_message CLOB,
                                   client_id NUMBER NOT NULL,
                                   campaign_id NUMBER,
                                   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                                   sent_at TIMESTAMP,
                                   read_at TIMESTAMP,
                                   deleted NUMBER(1) DEFAULT 0,
                                   CONSTRAINT fk_wtc_notifications_client
                                       FOREIGN KEY (client_id) REFERENCES wtc_clients (id),
                                   CONSTRAINT fk_wtc_notifications_campaign
                                       FOREIGN KEY (campaign_id) REFERENCES wtc_campaigns (id)
);

CREATE TABLE wtc_audits (
                            id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            action VARCHAR(255) NOT NULL,
                            details CLOB,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                            user_id NUMBER,
                            entity_id NUMBER,
                            entity_name VARCHAR(255),
                            deleted NUMBER(1) DEFAULT 0,
                            CONSTRAINT fk_wtc_audits_user
                                FOREIGN KEY (user_id) REFERENCES wtc_users (id)
);

CREATE TABLE client_segments (
                                 client_id NUMBER NOT NULL,
                                 segment_id NUMBER NOT NULL,

                                 PRIMARY KEY (client_id, segment_id),

                                 CONSTRAINT fk_client_segments_client
                                     FOREIGN KEY (client_id) REFERENCES wtc_clients (id),
                                 CONSTRAINT fk_client_segments_segment
                                     FOREIGN KEY (segment_id) REFERENCES wtc_segments (id)
);

CREATE TABLE client_tags (
                             client_id NUMBER NOT NULL,
                             tag_id NUMBER NOT NULL,

                             PRIMARY KEY (client_id, tag_id),
                             CONSTRAINT fk_client_tags_client
                                 FOREIGN KEY (client_id) REFERENCES wtc_clients (id),
                             CONSTRAINT fk_client_tags_tag
                                 FOREIGN KEY (tag_id) REFERENCES wtc_tags (id)
);